# If this version is changed, amend the edition set in `Cargo.toml`.
edition = "2024"
style_edition = "2024"
unstable_features = true
# Prevent accidental formatting with an incompatible rustfmt release.
required_version = "1.9.0"

# Better readability
format_code_in_doc_comments = true
wrap_comments = true
normalize_comments = true
format_strings = true

# Consistency
newline_style = "Unix"
normalize_doc_attributes = true
use_field_init_shorthand = true
imports_layout = "HorizontalVertical"
group_imports = "StdExternalCrate"
imports_granularity = "Module"

# Wrapping
comment_width = 80
max_width = 100
